[package]
name = "public"
version = "0.1.0"
edition = "2021"

[lib]
name = "public"
path = "src/lib.rs"

[dependencies]
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"

getrandom = { version = "0.3", features = ["wasm_js"], default-features = false } # for wasm
base64 = "0.22.1"
