[package]
name = "dynamic_code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rune = "0.13.4"
rune-modules = "0.13.4"
serde = "1.0.219"
serde_json = "1.0.140"
public = { path = "../public" }
once_cell = "1.21.3"
